name: Autoprefixer
on:
  push:
    branches:
      - main
jobs:
  autoprefixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to latest commit
        uses: actions/checkout@v3.2.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "15.x"

      - name: Run autoprefixer
        run: |
          npm install postcss postcss-cli autoprefixer --save-dev
          npm run autoprefixer
